// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXooY9_me2NsIS1IawDhPuJDpmIBwn73E',
    appId: '1:834749742869:web:c5168f7f38a6e413ceb31c',
    messagingSenderId: '834749742869',
    projectId: 'employee-db-acd36',
    authDomain: 'employee-db-acd36.firebaseapp.com',
    databaseURL: 'https://employee-db-acd36-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-acd36.appspot.com',
    measurementId: 'G-4JD9YMVRSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBidq8GNk_Yci31fUl8vcx1gPgJVCbFexs',
    appId: '1:834749742869:android:5caae18c643bf4c3ceb31c',
    messagingSenderId: '834749742869',
    projectId: 'employee-db-acd36',
    databaseURL: 'https://employee-db-acd36-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-acd36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa310MLL9NesDVjm5YJ-efFFZvcpRyo7o',
    appId: '1:834749742869:ios:fa5608eaafca031dceb31c',
    messagingSenderId: '834749742869',
    projectId: 'employee-db-acd36',
    databaseURL: 'https://employee-db-acd36-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-acd36.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa310MLL9NesDVjm5YJ-efFFZvcpRyo7o',
    appId: '1:834749742869:ios:fa5608eaafca031dceb31c',
    messagingSenderId: '834749742869',
    projectId: 'employee-db-acd36',
    databaseURL: 'https://employee-db-acd36-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-acd36.appspot.com',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXooY9_me2NsIS1IawDhPuJDpmIBwn73E',
    appId: '1:834749742869:web:1456165ca1cb83e7ceb31c',
    messagingSenderId: '834749742869',
    projectId: 'employee-db-acd36',
    authDomain: 'employee-db-acd36.firebaseapp.com',
    databaseURL: 'https://employee-db-acd36-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-acd36.appspot.com',
    measurementId: 'G-C2C1MYKDEH',
  );

}